theme: jekyll-theme-cayman

# Site settings
domain: imgmath.github.io
url: "https://imgmath.github.io"
baseurl: ""

title: ImgMath Lab
description: Image Processing and Analysis Lab
keywords: [Image Processing, Video Analysis, Computer Vision]

author: ImgMath Lab

show_download: false
show_github: false

# Mobile settings
mobile_nav_breakpoint: 768px

# Build settings
markdown_ext: md

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"


